# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FourierMachines.Ani.Client.BOIP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FourierMachines.Ani.Client.BOIP

  target 'FourierMachines.Ani.Client.BOIPTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
