# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AniDream' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AniDream
  pod "FMDB"
  pod 'AudioKit'
 
  target 'AniDreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AniDreamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
