# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FourierMachines.Ani.Client.AI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Starscream', '~> 3.0.2'
  pod 'FMDB'
  # Pods for FourierMachines.Ani.Client.AI

  target 'FourierMachines.Ani.Client.AITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
